# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'searchLib' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'searchLib', :path => "./"
  pod 'MBProgressHUD', '~> 1.0.0'
  # Pods for searchLib

  target 'searchLibTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
